service: integration-service
useDotenv: true

provider:
  name: aws
  runtime: nodejs16.x
  stage: production
  region: eu-central-1
  timeout: 300
  memorySize: 256
  architecture: arm64
  iam:
    role:
      statements:
        - Effect: Allow
          Action: 
            - "lambda:InvokeFunction"
          Resource: '*'
functions:
  app:
    handler: dist/lambda.handler
    url: true
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true